# blueprints/create_directory_bp.py
# This file was auto-generated by the AVM's create_new_tool blueprint.
from foundry.blueprints import Blueprint
from foundry.actions import create_directory

# Parameters schema for the LLM, provided by the Genesis prompt
params = {
  "type": "object",
  "properties": {
    "path": {
      "type": "string"
    }
  },
  "required": [
    "path"
  ]
}

blueprint = Blueprint(
    id="create_directory",
    description="Creates a new, empty directory at the specified path.",
    parameters=params,
    action_function=create_directory
)
