# blueprints/run_shell_command_bp.py
# This file was auto-generated by Aura's create_new_tool blueprint.
from foundry.blueprints import Blueprint

# Parameters schema for the LLM, generated by the Genesis Tool.
params = {
    "type": "object",
    "properties": {
        "command": {
            "type": "string",
            "description": "The shell command to execute."
        }
    },
    "required": [
        "command"
    ]
}

blueprint = Blueprint(
    id="run_shell_command",
    description="Executes a shell command and returns its output.",
    parameters=params,
    action_function_name="run_shell_command"
)
